### ISSUE TITLE
Add carousel controls

### ISSUE THREAD

**Issue by RuanAragao** [RuanAragao/saudeflix#2]
Add next/prev carousel controls. Its use a Owl Carousel jQuery lib.

<img width="634" alt="Captura de Tela 2023-10-03 às 10 52 04" src="https://github.com/RuanAragao/saudeflix/assets/1015013/59241189-c722-44af-96e2-832cd6ca1b63">

**Comment by hemanth110702** [comment]
Hey, I would like to work on this. Can you please assign this to me?

**Comment by RuanAragao** [comment]
> Hey, I would like to work on this. Can you please assign this to me?

Sure!
